from typing import Protocol, Any


class StatsClientProtocol(Protocol):
    async def get_athlete_info_async(self, athlete_id: str) -> Any: ...

    async def get_athlete_stats_async(self, athlete_id: str) -> Any: ...

    def get_team_info(self, team_id: str) -> Any: ...

    def get_team_depth_chart(self, team_id: str) -> Any: ...
